framework:
    secret: '%env(APP_SECRET)%'

    # ✅ CSRF protection activada
    csrf_protection: true

    # ✅ Configuración segura y explícita de sesiones
    session:
        handler_id: null
        cookie_secure: auto
        cookie_samesite: lax
