framework:
    secret: '%env(APP_SECRET)%'
    csrf_protection: true

    session:
        handler_id: app.pdo_session_handler
        cookie_secure: auto
        cookie_samesite: lax
        cookie_lifetime: 0
        cookie_httponly: true
