security:
    password_hashers:
        App\Entity\User:
            algorithm: auto

    providers:
        app_user_provider:
            id: App\Security\UserProvider

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            lazy: true
            provider: app_user_provider
            form_login:
                login_path: login
                check_path: login
                default_target_path: /
            logout:
                path: /logout
                target: /

    access_control:
        - { path: ^/register, roles: PUBLIC_ACCESS }
        - { path: ^/login$, roles: PUBLIC_ACCESS }
        - { path: ^/, roles: ROLE_USER }
        - { path: ^/superadmin, roles: ROLE_SUPER_ADMIN }
        - { path: ^/carta, roles: ROLE_SUPER_ADMIN }
        - { path: ^/test-db, roles: PUBLIC_ACCESS }
