services:
  - type: web
    name: cards-and-shots-dev
    runtime: docker
    buildCommand: |
      composer install --no-dev --optimize-autoloader
      php bin/console cache:clear --env=prod
    startCommand: symfony server:start --no-tls --port=$PORT
    envVars:
      - key: APP_ENV
        value: dev
      - key: APP_SECRET
        generateValue: true
      - key: DATABASE_URL
        value: mysql://root:jgPyYLJkcKnJAiESzAjQjknHMxRDQEia@turntable.proxy.rlwy.net:12815/railway
      - key: MAILER_DSN
        value: null://null
    healthCheckPath: /test-db
    autoDeploy: true
    branch: developing 