services:
  - type: web
    name: cards-and-shots
    env: docker
    plan: free
    envVars:
      - key: APP_ENV
        value: prod
      - key: APP_SECRET
        value: changeme123
      - key: DATABASE_URL
        value: mysql://mysql:castillo69@cardnshots-mysql:3306/cardnshots

  - type: mysql
    name: cardnshots-mysql
    ipAllowList: []
    plan: free