services:
  - type: web
    name: cards-and-shots
    env: docker
    plan: free
    buildCommand: composer install --no-dev --optimize-autoloader
    startCommand: |
      php bin/console doctrine:migrations:migrate --no-interaction
      php -S 0.0.0.0:8000 -t public
    envVars:
      - key: APP_ENV
        value: prod
      - key: APP_SECRET
        value: changeme123
      - key: DATABASE_URL
        sync: false
      - key: MESSENGER_TRANSPORT_DSN
        value: doctrine://default?auto_setup=0
      - key: MAILER_DSN
        value: null://null