services:
  - type: web
    name: cards-and-shots
    runtime: docker
    envVars:
      - key: APP_ENV
        value: prod
      - key: APP_DEBUG
        value: "0"
      - key: APP_SECRET
        generateValue: true
      - key: DATABASE_URL
        value: mysql://root:jgPyYLJkcKnJAiESzAjQjknHMxRDQEia@turntable.proxy.rlwy.net:12815/railway
      - key: MAILER_DSN
        value: null://null
    healthCheckPath: /
    autoDeploy: true
    branch: main
