<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerWlwwjaM\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerWlwwjaM/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerWlwwjaM.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerWlwwjaM\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerWlwwjaM\App_KernelDevDebugContainer([
    'container.build_hash' => 'WlwwjaM',
    'container.build_id' => '5c78a596',
    'container.build_time' => 1743720307,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerWlwwjaM');
