parameters:

services:
    app.pdo_session_handler:
        class: Symfony\Component\HttpFoundation\Session\Storage\Handler\PdoSessionHandler
        arguments:
            $pdoOrDsn: '%env(resolve:DATABASE_URL)%'
            $options:
                db_table: sessions
                db_id_col: sess_id
                db_data_col: sess_data
                db_time_col: sess_time
                db_lifetime_col: sess_lifetime

    App\Security\UserProvider:
        arguments:
            $userRepository: '@App\Repository\UserRepository'

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'
